/* NESTO concept catalog. IDs are stable so saved carts and deep links keep working. */
window.NestoCatalog = (() => {
  const rows = [
    [
      0,
      'LUNE 라운드 다이닝 테이블',
      'table',
      'catalog/lune-table.webp',
      890000,
      623000,
      '매트 화이트 상판과 가볍게 뻗은 우드 다리. 두 사람의 식사부터 작은 홈카페까지.',
      ['화이트 / 오크', '웜 그레이 / 오크'],
      'Ø900 × H740 mm',
      '라미네이트 상판 · 오크 다리',
      ['dining', 'kitchen'],
    ],
    [
      1,
      'MILO 라운드 2인 소파',
      'sofa',
      'catalog/milo-sofa.webp',
      1280000,
      960000,
      '둥글게 감싸는 프레임과 넉넉한 쿠션으로 창가에 나만의 휴식 공간을 만듭니다.',
      ['크림 아이보리', '샌드 베이지'],
      'W1600 × D1050 × H780 mm',
      '라탄 프레임 · 폴리에스터 패브릭 · 고밀도 폼',
      ['living'],
    ],
    [
      2,
      'NOVA 월넛 사이드보드',
      'storage',
      'catalog/nova-sideboard.webp',
      1450000,
      942500,
      '깊은 월넛 톤과 클래식한 다리의 조화. 오래 아끼는 식기와 소품을 차분히 정돈합니다.',
      ['월넛', '허니 브라운'],
      'W1200 × D420 × H860 mm',
      '월넛 무늬목 · 원목 다리 · 합판',
      ['living', 'dining'],
    ],
    [
      3,
      'ARCO 라운지 체어',
      'chair',
      'catalog/arco-chair.webp',
      760000,
      608000,
      '손끝에 닿는 매끄러운 우드 암레스트, 몸을 받쳐주는 패브릭 쿠션. 책 한 권과 함께하는 자리.',
      ['오트밀', '토프'],
      'W720 × D780 × H780 mm',
      '애쉬 원목 · 패브릭 · 고밀도 폼',
      ['living', 'bedroom'],
    ],
    [
      4,
      'ELIN 원목 가든 벤치',
      'chair',
      'catalog/elin-bench.webp',
      540000,
      388000,
      '나뭇결을 그대로 살린 넓은 좌석. 베란다와 정원에 잠시 쉬어 갈 여유를 더합니다.',
      ['내추럴 우드'],
      'W1400 × D540 × H820 mm',
      '아카시아 원목 · 실외용 오일 마감',
      ['living', 'dining'],
    ],
    [
      5,
      'MORI 우드 거실장',
      'storage',
      'catalog/mori-console.webp',
      1180000,
      802400,
      '슬림한 다리와 넓은 수납공간. 낮고 긴 비율로 거실의 중심을 단정하게 잡아줍니다.',
      ['월넛', '내추럴 오크'],
      'W1600 × D400 × H600 mm',
      '우드 무늬목 · 합판 · 원목 다리',
      ['living'],
    ],
    [
      6,
      '루아 원목 다이닝 테이블',
      'table',
      'catalog/lua-table.webp',
      890000,
      890000,
      '손길이 닿을수록 편안한 오크 상판. 가족의 식사와 주말의 작업을 넉넉히 품는 테이블.',
      ['내추럴 오크', '스모크 오크'],
      'W1600 × D800 × H740 mm',
      '오크 원목 · 수성 도장',
      ['dining', 'kitchen'],
    ],
    [
      7,
      '모노 패브릭 소파 3인',
      'sofa',
      'catalog/mono-sofa.webp',
      1590000,
      1272000,
      '담백한 직선과 포근한 쿠션감. 다리를 뻗고 하루를 마무리하기 좋은 데일리 소파.',
      ['웜 그레이', '샌드 베이지'],
      'W2200 × D920 × H820 mm',
      '폴리에스터 패브릭 · 목재 프레임 · 고밀도 폼',
      ['living'],
    ],
    [
      8,
      '오브 오픈 사이드 테이블',
      'table',
      'catalog/orb-table.webp',
      320000,
      320000,
      '컵은 위에, 책은 아래에. 두 층의 열린 선반으로 작은 자리를 알뜰하게 쓰세요.',
      ['내추럴 오크', '월넛'],
      'W420 × D380 × H560 mm',
      '오크 원목 · 우드 무늬목',
      ['living', 'bedroom'],
    ],
    [
      9,
      '리브 원목 체어',
      'chair',
      'catalog/liv-chair.webp',
      390000,
      390000,
      '등을 받치는 곡면과 가벼운 실루엣. 식탁 앞에서도 책상 앞에서도 자연스럽습니다.',
      ['내추럴 오크', '화이트 오크'],
      'W470 × D510 × H800 mm · SH450',
      '성형 합판 · 애쉬 원목',
      ['dining', 'kitchen'],
    ],
    [
      10,
      '아르코 플로어 램프',
      'light',
      'catalog/arco-lamp.webp',
      450000,
      450000,
      '아치 아래로 은은하게 퍼지는 빛. 소파 옆을 조용한 독서 공간으로 바꿔줍니다.',
      ['올리브', '차콜'],
      'W380 × D480 × H1520 mm',
      '분체 도장 스틸 · E26 소켓',
      ['living', 'bedroom'],
    ],
    [
      11,
      '베르 낮은 수납장',
      'storage',
      'catalog/ver-storage.webp',
      980000,
      980000,
      '수평으로 흐르는 나뭇결과 둥근 모서리. 문을 닫으면 생활의 흔적도 단정해집니다.',
      ['내추럴 오크', '화이트 오크'],
      'W1400 × D400 × H650 mm',
      '오크 무늬목 · 합판 · 원목 다리',
      ['living', 'dining', 'kitchen'],
    ],
    [
      12,
      '누아 라운지 체어',
      'chair',
      'catalog/noir-chair.webp',
      760000,
      646000,
      '기울어진 등받이와 길게 이어지는 암레스트. 깊이 기대어 쉬는 시간을 위한 체어.',
      ['차콜', '모스 그린'],
      'W680 × D850 × H980 mm',
      '비치 원목 · 패브릭 · 탄성 웨빙',
      ['living', 'bedroom'],
    ],
    [
      13,
      '오트 침실 협탁',
      'table',
      'catalog/oat-nightstand.webp',
      290000,
      290000,
      '잠들기 전 읽던 책과 작은 조명. 서랍 하나로 침대 곁의 일상을 깔끔히 담습니다.',
      ['허니 오크', '내추럴 오크'],
      'W450 × D400 × H500 mm',
      '오크 원목 · 합판 · 우드 손잡이',
      ['bedroom', 'living'],
    ],
    [
      14,
      '셀린 4단 서랍장',
      'storage',
      'catalog/celine-dresser.webp',
      1120000,
      1120000,
      '밝은 크림색 서랍과 우드 프레임. 옷과 소품을 나누어 담는 산뜻한 수납 가구.',
      ['크림 / 오크', '샌드 / 오크'],
      'W750 × D450 × H1080 mm',
      '우드 무늬목 · 도장 MDF · 금속 레일',
      ['bedroom', 'living'],
    ],
    [
      15,
      '엘로우 벤치 소파',
      'sofa',
      'catalog/ellow-sofa.webp',
      690000,
      586500,
      '둥근 쿠션과 낮은 우드 베이스. 아담한 거실과 침실에 부드러운 포인트를 더합니다.',
      ['크림 부클레', '오트밀'],
      'W1500 × D720 × H730 mm',
      '부클레 패브릭 · 오크 베이스 · 폼',
      ['living', 'bedroom'],
    ],
    [
      16,
      '마레 라운드 거울',
      'decor',
      'catalog/mare-mirror.webp',
      280000,
      280000,
      '빛을 담아 공간을 넓히는 둥근 프레임. 콘솔 위에 두어도 벽에 걸어도 좋습니다.',
      ['내추럴 우드', '월넛'],
      'Ø600 × D30 mm',
      '유리 거울 · 우드 프레임',
      ['living', 'bedroom'],
    ],
    [
      17,
      '플로우 원목 책상',
      'table',
      'catalog/flow-desk.webp',
      740000,
      592000,
      '창가에 놓고 싶은 넓은 작업대. 선명한 우드 결이 집중하는 시간에도 온기를 전합니다.',
      ['내추럴 오크', '월넛'],
      'W1400 × D650 × H740 mm',
      '오크 무늬목 · 합판 · 스틸 다리',
      ['living', 'bedroom'],
    ],
    [
      18,
      'SERA 오크 퀸 침대',
      'bed',
      'catalog/sera-bed.webp',
      1490000,
      1266500,
      '가로로 이어지는 오크 헤드와 낮은 프레임. 햇살이 오래 머무는 편안한 침실을 만듭니다.',
      ['내추럴 오크', '스모크 오크'],
      'W1600 × D2150 × H920 mm · Q 1500×2000',
      '오크 원목 · 합판 깔판',
      ['bedroom'],
    ],
    [
      19,
      'MELLOW 부클레 퀸 침대',
      'bed',
      'catalog/mellow-bed.webp',
      1690000,
      1436500,
      '둥근 헤드보드와 보송한 부클레. 기대어 앉는 저녁부터 느긋한 아침까지 포근하게.',
      ['크림 부클레', '오트밀'],
      'W1700 × D2200 × H1000 mm · Q 1500×2000',
      '부클레 패브릭 · 목재 프레임 · 폼',
      ['bedroom'],
    ],
    [
      20,
      'RUNE 수납 싱글 침대',
      'bed',
      'catalog/rune-bed.webp',
      1090000,
      981000,
      '침대 아래에 숨긴 두 개의 서랍. 작은 방에서도 이불과 계절 옷을 여유롭게 정리하세요.',
      ['내추럴 오크', '화이트 오크'],
      'W1100 × D2100 × H850 mm · SS 1100×2000',
      '오크 무늬목 · 합판 · 금속 레일',
      ['bedroom'],
    ],
    [
      21,
      'PODO 머쉬룸 테이블 램프',
      'light',
      'catalog/podo-lamp.webp',
      179000,
      161100,
      '오렌지빛 작은 오브제. 둥근 갓 아래 퍼지는 따뜻한 빛으로 책상과 침대 곁을 채웁니다.',
      ['번트 오렌지', '버터 크림'],
      'Ø240 × H320 mm',
      '유광 도장 스틸 · E14 소켓',
      ['living', 'bedroom', 'kitchen'],
    ],
    [
      22,
      'LUMI 플리츠 펜던트',
      'light',
      'catalog/lumi-pendant.webp',
      259000,
      233100,
      '주름 사이로 번지는 부드러운 빛. 식탁 위에 걸어 매일의 식사를 아늑하게 만듭니다.',
      ['리넨 아이보리', '샌드'],
      'Ø500 × H320 mm · 코드 1500 mm',
      '리넨 혼방 갓 · 스틸 · E26 소켓',
      ['dining', 'kitchen', 'bedroom'],
    ],
    [
      23,
      'SOL 울 블렌드 러그',
      'decor',
      'catalog/sol-rug.webp',
      329000,
      296100,
      '맨발에 기분 좋은 촉감과 은은한 입체 패턴. 거실과 침실에 차분한 바탕을 깔아줍니다.',
      ['오트밀', '웜 그레이'],
      'W1600 × D2300 mm · 두께 12 mm',
      '울 80% · 코튼 20%',
      ['living', 'bedroom'],
    ],
    [
      24,
      'ONDA 세라믹 베이스',
      'decor',
      'catalog/onda-vase.webp',
      69000,
      62100,
      '모래를 닮은 표면과 유연한 곡선. 꽃 한 송이 없이도 선반 위를 채우는 작은 조형물.',
      ['샌드', '초크 화이트'],
      'W160 × D130 × H260 mm',
      '유약 마감 도자기',
      ['living', 'dining', 'kitchen', 'bedroom'],
    ],
    [
      25,
      'PUFF 부클레 2인 소파',
      'sofa',
      'catalog/puff-sofa.webp',
      1190000,
      952000,
      '구름처럼 둥근 실루엣과 포근한 크림 부클레. 둘이 함께 쉬는 시간을 부드럽게 감싸줍니다.',
      ['크림 부클레'],
      'W1600 × D900 × H780 mm',
      '부클레 패브릭 · 목재 프레임 · 고밀도 폼',
      ['living'],
    ],
    [
      26,
      'HUG 부클레 라운지 체어',
      'chair',
      'catalog/hug-chair.webp',
      590000,
      472000,
      '몸을 감싸는 곡선과 폭신한 부클레의 만남. 좋아하는 책과 함께 나만의 아늑한 자리를 만드세요.',
      ['크림 부클레'],
      'W850 × D820 × H760 mm',
      '부클레 패브릭 · 목재 프레임 · 고밀도 폼',
      ['living', 'bedroom'],
    ],
    [
      27,
      'TOTO 오렌지 사이드 테이블',
      'table',
      'catalog/toto-table.webp',
      190000,
      152000,
      '둥근 상판과 볼륨 있는 다리에 담은 오렌지빛 포인트. 소파 곁에 커피 한 잔의 여유를 더합니다.',
      ['오렌지'],
      'Ø400 × H450 mm',
      '우레탄 도장 · 성형 합판',
      ['living', 'bedroom'],
    ],
  ];
  const care = {
    table: '컵 받침을 사용하고 물기는 즉시 닦아주세요. 뜨거운 냄비를 직접 올리지 마세요.',
    sofa: '부드러운 브러시로 먼지를 제거하고, 오염은 마른 천으로 눌러 닦아주세요. 커버는 전문 세탁을 권장합니다.',
    chair: '연결 부위를 주기적으로 확인하고 바닥 보호 패드를 사용해주세요.',
    storage:
      '무거운 물건은 아래 칸에 보관하고 수평을 맞춰 설치해주세요. 높은 수납장은 벽 고정을 권장합니다.',
    bed: '깔판 주변을 주기적으로 환기하고 연결 볼트를 확인해주세요. 매트리스는 별도 구성입니다.',
    light: '전원을 분리한 뒤 마른 천으로 닦아주세요. 소켓 규격에 맞는 LED 전구를 사용해주세요.',
    decor: '직사광선과 충격을 피하고 부드러운 도구로 먼지를 제거해주세요.',
  };
  return rows.map(
    ([id, name, group, image, original, price, desc, colors, dimensions, material, spaces]) => ({
      id,
      name,
      group,
      image,
      original,
      price,
      desc,
      colors,
      dimensions,
      material,
      spaces,
      signature: id >= 25,
      discount: Math.round((1 - price / original) * 100),
      fresh: id >= 18 || [6, 9, 11, 14].includes(id),
      likes: 18 + ((id * 17) % 143),
      rating: window.NestoReviews[id]?.length
        ? (window.NestoReviews[id].reduce((sum, r) => sum + r[1], 0) / window.NestoReviews[id].length).toFixed(1)
        : '—',
      reviewCount: window.NestoReviews[id]?.length || 0,
      care: care[group],
      delivery: ['light', 'decor'].includes(group) ? '택배배송 · 3–5일' : '전문 설치배송 · 7–14일',
      gallery: ['product', 'room', 'material', 'side'],
      reviews: window.NestoReviews[id] || [],
    }),
  );
})();
