(() => {
const products=[
{name:'POM 라운지 체어',desc:'동그란 휴식, 기분 좋은 오렌지',price:608000,original:760000,scene:4,group:'chair'},
{name:'CLOUD 패브릭 소파',desc:'내 몸을 포근하게 감싸는 곡선',price:960000,original:1280000,scene:5,group:'sofa'},
{name:'POP 사이드 테이블',desc:'작은 공간을 밝히는 컬러 포인트',price:189000,original:210000,scene:6,group:'table'},
{name:'MORI 오크 사이드보드',desc:'따뜻한 결, 깔끔한 일상의 수납',price:802400,original:1180000,scene:7,group:'storage'},
{name:'LUNE 라운드 테이블',desc:'함께하는 순간을 위한 라운드 테이블',price:623000,original:890000,scene:1,group:'table'},
{name:'COZY 패브릭 침대',desc:'포근한 하루의 시작과 끝',price:1120000,original:1400000,scene:3,group:'bed'}];
const money=value=>value.toLocaleString('ko-KR');
const scene=(index,label)=>'<div class="scene scene-'+index+'" role="img" aria-label="'+label+'"></div>';
const card=(p,index)=>'<a class="product-card" href="?screen=product&id='+index+'">'+scene(p.scene,p.name)+'<h3>'+p.name+'</h3><p>'+p.desc+'</p><div class="price"><b>'+Math.round((1-p.price/p.original)*100)+'%</b><strong>'+money(p.price)+'원</strong><del>'+money(p.original)+'</del></div><div class="rating">★ 4.9 · NESTO COLLECTION</div></a>';
const cards=items=>'<div class="products-grid">'+items.map(p=>card(p,products.indexOf(p))).join('')+'</div>';
const params=new URLSearchParams(location.search),mode=params.get('screen')||'home',root=document.querySelector('#shop-content');
if(mode==='list'){
root.innerHTML='<section class="catalog-title"><p class="eyebrow">FIND YOUR EVERYDAY FAVORITES</p><h1>MAKE ROOM<br>FOR YOU.</h1><p>당신의 공간을 채울, 좋아하는 가구.</p><div class="filters" aria-label="상품 종류">'+[['all','전체'],['sofa','소파'],['chair','체어'],['table','테이블'],['bed','침대'],['storage','수납']].map(([id,label])=>'<button data-filter="'+id+'" aria-pressed="'+(id==='all')+'">'+label+'</button>').join('')+'</div></section><section class="shop-section catalog" aria-live="polite">'+cards(products)+'</section>';
root.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{root.querySelectorAll('[data-filter]').forEach(item=>item.setAttribute('aria-pressed',String(item===button)));root.querySelector('.catalog').innerHTML=cards(products.filter(p=>button.dataset.filter==='all'||p.group===button.dataset.filter));}));
}else if(mode==='product'){
const id=Number(params.get('id')??1),p=products[id]||products[1];
root.innerHTML='<div class="crumb"><a href="?screen=home">HOME</a> / <a href="?screen=list">COLLECTION</a> / '+p.name+'</div><section class="detail-grid">'+scene(p.scene,p.name)+'<div class="detail-info"><p class="eyebrow">NESTO / EVERYDAY COMFORT</p><h1>'+p.name+'</h1><p>'+p.desc+'</p><div class="price"><b>'+Math.round((1-p.price/p.original)*100)+'%</b><strong>'+money(p.price)+'원</strong><del>'+money(p.original)+'원</del></div><div class="delivery">배송 안내 &nbsp; 전문 설치배송<br>소재와 관리 &nbsp; 상품에 맞는 관리 안내 제공</div><label for="color">컬러<select id="color"><option>'+([4,6].includes(p.scene)?'오렌지':p.group==='table'||p.group==='storage'?'내추럴 오크':'크림 아이보리')+'</option></select></label><div class="quantity"><span>수량</span><button data-minus aria-label="수량 줄이기">−</button><output data-quantity>1</output><button data-plus aria-label="수량 늘리기">+</button></div><div class="total"><span>총 상품 금액</span><strong data-total>'+money(p.price)+'원</strong></div><a class="detail-cta" href="?screen=list">컬렉션 더 살펴보기 →</a><p class="detail-note">상품 구성과 가격은 디자인 표현을 위한 예시입니다.</p></div></section><nav class="detail-tabs"><a href="#info">상품정보</a><a href="#care">소재 및 관리</a></nav><section class="detail-story" id="info"><p class="eyebrow">YOUR NEW FAVORITE PLACE</p><h2>일상에 편안함을 더하는,<br>'+p.name+'</h2><p>'+p.desc+'.<br>좋아하는 가구와 함께 나다운 공간을 완성해 보세요.</p>'+scene(p.scene,p.name)+'<h2 id="care">오래 함께하는 일상.</h2><p>부드러운 천으로 가볍게 관리하고<br>직사광선과 습기를 피해 사용해 주세요.</p></section>';
let quantity=1;function update(){root.querySelector('[data-quantity]').textContent=quantity;root.querySelector('[data-total]').textContent=money(quantity*p.price)+'원';root.querySelector('[data-minus]').disabled=quantity===1;root.querySelector('[data-plus]').disabled=quantity===99;}
root.querySelector('[data-minus]').onclick=()=>{quantity=Math.max(1,quantity-1);update();};root.querySelector('[data-plus]').onclick=()=>{quantity=Math.min(99,quantity+1);update();};update();
}else{
root.innerHTML='<section class="shop-hero"><img src="assets/nesto/hero.png" alt="오렌지 공간의 크림 소파"><div class="shop-hero-copy"><p class="eyebrow">A LITTLE COLOR. A LOT OF COMFORT.</p><h1>MAKE YOURSELF<br>AT HOME.</h1><p>나의 가장 편안한 곳, nesto.</p><a class="pill" href="?screen=list">나의 가구 만나기 ↗</a></div></section><div class="shop-strip">SOFT SHAPES. SUNNY DAYS. &nbsp; 편안한 일상을 위한 작은 변화.</div><section class="shop-section" id="spaces"><header class="shop-heading"><div><h2>SHOP BY SPACE</h2><p>좋아하는 공간에서 시작하는 나다운 집.</p></div><a href="?screen=list">VIEW ALL ↗</a></header><div class="spaces-grid">'+['LIVING','DINING','KITCHEN','BEDROOM'].map((name,i)=>'<a class="space-card" href="?screen=list">'+scene(i,name+' 인테리어')+'<h3>'+name+' ↗</h3></a>').join('')+'</div></section><section class="shop-section" id="stories"><header class="shop-heading"><div><h2>STORIES FROM HOME</h2><p>우리의 일상을 조금 더 좋아지게 하는 것들.</p></div><a href="?screen=list">VIEW ALL ↗</a></header>'+cards(products.slice(0,4))+'</section><section class="editorial">'+scene(0,'밝고 포근한 크림 소파 거실')+'<div><p class="eyebrow">THE SLOW SUNDAY EDIT</p><h2>A SOFTER<br>KIND OF DAY.</h2><p>조금 느려도 괜찮은 하루.<br>햇빛이 드는 자리에, 나만의 편안함을 놓아보세요.</p><a class="text-link" href="?screen=list">편안한 일상 만나기 ↗</a></div></section><section class="shop-section"><header class="shop-heading"><div><h2>BETTER DAYS, SAME NESTO.</h2><p>매일의 새로운 취향을 발견해 보세요.</p></div></header>'+cards(products.slice(2))+'</section>';
}
})();